### ISSUE TITLE
Guidance for Python Developers

### ISSUE THREAD

**Issue by HassanA99** [charl1e7/rust-translators#1]
Hello! I'm a Python developer interested in using the translators library in my projects. Could you please provide guidance on how Python developers can effectively integrate and utilize this translators library?

**Comment by charl1e7** [comment]
I can try to port this library to python via "PyO3", or you can simply write a small code that does the same thing, but only slightly cut down for your task.

**Comment by charl1e7** [comment]
I accidentally closed the question, sorry

**Comment by charl1e7** [comment]
[translators.zip](https://github.com/user-attachments/files/16126139/translators.zip)

Example of using my library in .dll format(for windows) on python(Write me if you need it for linux)
