### ISSUE TITLE
This crate doesn't compile for Android

### ISSUE THREAD

**Issue by ndpm13** [charl1e7/rust-translators#2]
I tried using this crate in a [Tauri](https://tauri.app) project but I couldn't build it for Android for some reason, the error was unclear and ridiculously long. Also the same project builds fine after removing the crate from `Cargo.toml`.

#### System Info
OS: Artix Linux (OpenRC)
Rust: Latest stable

**Comment by charl1e7** [comment]
The error is coming from the "reqwest" library. You can simply create an empty repository with `openssl-sys = { version = "x", features = ["vendored"] }` and try to figure out why it can't build with `cargo build --target armv7-linux-androideabi`

**Comment by charl1e7** [comment]
Added android compilation support in 0.15.
![my screenshot from android
](https://github.com/user-attachments/assets/34f23fd5-43cc-4f98-8446-6860d4a3629e)
My screenshot from android.
